name: my-action

on:
  push:
    branches:
      - main

jobs:
 frontend:
    runs-on: ubuntu-latest

    #defaults:
     # run:
      #  working-directory: frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
      - name: Show Files
  run: |
    pwd
    ls -la
    find . -name package.json

      - name: Install Packages
        run: npm install

      - name: Start Application
        run: npm start